# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 20:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firm',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Firm'),
        ),
    ]
