# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_frequentlysearched_latestsearches_soldvehicles_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(null=True),
        ),
    ]
