# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20171213_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='firm_manager_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
