# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20171216_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.Firm'),
        ),
    ]
