# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 11:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20171216_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='manager',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='firm_manager_user', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
