# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 11:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20171216_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.FileField(upload_to='images/%Y/%m/%d'),
        ),
    ]
