# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20171217_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='path',
            field=models.CharField(max_length=100),
        ),
    ]
