# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 22:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_auto_20171217_2113'),
        ('shop', '0013_auto_20171217_2057'),
    ]

    operations = [
    ]
