# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 22:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_merge_20171217_2206'),
        ('shop', '0014_auto_20171217_2159'),
    ]

    operations = [
    ]
