# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-17 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_merge_20171217_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='photo',
            field=models.FileField(upload_to=''),
        ),
    ]
