# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 10:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_auto_20171217_2255'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soldvehicles',
            name='photo',
        ),
    ]
